CREATE TABLE address (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    street_number INTEGER NOT NULL,
    street_name VARCHAR(255),
    suburb VARCHAR(255),
    postcode VARCHAR(255),
    city VARCHAR(255),
    state VARCHAR(255),
    PRIMARY KEY (id)
);