name: Run tests
on:
  push:
    branches:
      - master

  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: 'self-hosted'

    steps:
      - name: Check out code
        uses: actions/checkout@v3


      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Run Clean Test
        run: mvn clean test

      - name: Build Native Image
        run: mvn -Pnative spring-boot:build-image -DREGISTRY_URL="${{ vars.REGISTRY_URL }}" -DskipTests

      - name: Docker Login
        uses: docker/login-action@v3
        with:
          registry: ${{ vars.REGISTRY_URL }}
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_TOKEN }}

      - name: Docker Push image
        run: docker push ${{ vars.REGISTRY_URL }}/springboot-cucumber-bdd:0.0.1-SNAPSHOT