name: Run tests
on:
  push:
    branches:
      - master

  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: 'self-hosted'

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Run Clean Test Build Native Image
        run: mvn clean -Pnative spring-boot:build-image -DREGISTRY_URL="${{ vars.REGISTRY_URL }}" -DskipTests

      - name: Docker Login
        run: docker login ${{ vars.REGISTRY_URL }} -u ${{ secrets.REGISTRY_USER }} -p ${{ secrets.REGISTRY_TOKEN }}

      - name: Docker Push image
        run: docker push ${{ vars.REGISTRY_URL }}/springboot-cucumber-bdd:0.0.1-SNAPSHOT